In [3]:
import numpy as np

In [4]:
python_list = range(1000000) # list from 0 to 100000000

In [5]:
python_list

range(0, 1000000)

In [6]:
numpy_array  = np.arange(1000000)

In [7]:
numpy_array 

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [8]:
# range return list and arange return array

### two mehtod to do this work 1st this programme and second is comprehension 
### we work on comprehension method 

In [9]:
results = []
for i in python_list :
    results.append(i*5)
    

In [10]:
#multiply a list with 5,1000 times using List comprehension

In [11]:
%time

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.48 µs


In [12]:
%time for i in range(1000): results = [i*5 for i in python_list] 

CPU times: user 40.7 s, sys: 552 ms, total: 41.2 s
Wall time: 41.3 s


In [13]:
numpy_array * 5

array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

# if we want to watch how much time it take we use"%timeit"
# or "%time"

In [14]:
%time numpy_array*5

CPU times: user 342 µs, sys: 3.94 ms, total: 4.28 ms
Wall time: 3.43 ms


array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

In [15]:
%timeit numpy_array * 5 

1.13 ms ± 50.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
%time for i in range(1000): result = numpy_array * 5  #it multi 1 by 1 till 1000 time

CPU times: user 1.33 s, sys: 4.03 ms, total: 1.33 s
Wall time: 1.33 s


# now as we can see that it only take 1,4 sec to compile same qustion as we do in list
# Summary the qustion is compare numpy array and python list
# the above code are explaining that is diffenent in below same thing we did for explain you

In [17]:
%time python_list

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 3.58 µs


range(0, 1000000)

In [18]:
%time numpy_array

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 3.1 µs


array([     0,      1,      2, ..., 999997, 999998, 999999])

# Numpy array creation Methods
### np.array(): convert input data to an ndarray
### np.zeros(): produces arrays of 0s
### np.ones(): produces arrays of 1s
### np.empty(): create new arrays by allocating new memory, but do not populate with any values
### np.arange(): like the built-in range but returns an ndarray instead of a list

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
one_d_array = np.zeros((10))
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
x = one_d_array + 5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
one_d_array =np.ones(10)
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
y = one_d_array*3
y

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [24]:
 # print 1 to 10 number throught numpuy
x = np.arange(1,10)

In [25]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
            #shape of array 
        #In 2d 5 is column 10 is row
np.zeros((10,5))     

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
y= np.zeros((5,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
#In 3d 4 is depths 2 is column 5 is row 
np.zeros((4,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
                                    # 4d
     #In 4d 4 is depths 2 is column 5 is row 2 6 is unknow
x=np.zeros((4,5,2,6))  #"""(4,5,2,6)<-- this is tuple"""
x

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [30]:
                    #shape: a tuple indicating the size of each dimension
                # it show previous dimesion used 
x.shape

(4, 5, 2, 6)

In [31]:
y.shape

(5, 5)

In [32]:
            # Arrary of user define by list 

In [33]:
        # now tell me which dimension is it
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x.shape

(12,)

In [34]:
y = np.array([1,2,3,4,5,6,67,7])
y.shape

(8,)

In [35]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
y=y.reshape(2,4)
y

array([[ 1,  2,  3,  4],
       [ 5,  6, 67,  7]])

In [37]:
t= x.reshape((2,3,2))
t

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [38]:
# now i want to find out what is shape of t 
t.shape

(2, 3, 2)

In [39]:
#ndim: the number of dimensions of the array
t.ndim

3

In [40]:
x.ndim

1

In [41]:
y.ndim

2

In [42]:
# Accessing individual elemts of array |

In [43]:
y[0,2] # it give us 3 bcz we told hime givr me that number which is on 2 index here are we #array([[ 1,  2,  3,  4],

3

In [44]:
y[0:2]

array([[ 1,  2,  3,  4],
       [ 5,  6, 67,  7]])

In [45]:
arr7 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr7

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr7.shape # total number 2 , total pair 2 total column 3


(2, 2, 3)

In [47]:
arr7.size# total number of element 


12

In [48]:
arr7.itemsize # total number of row 

8

In [49]:
arr7.astype('float') #convert the datatype


array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [50]:
x=np.empty(2)

In [51]:
x

array([-2.00000000e+000,  1.72693856e-315])

In [52]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(4,3)

In [55]:
y.itemsize

8

In [56]:
y.size

12

In [57]:
y.dtype

dtype('int64')

In [58]:
y.astype('float')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [65]:
z = x.reshape(2,2,3)
z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
z[0:3,1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [72]:
x = np.array([1,2,3,6,7,8,9,12])
x
        # now tell me which dimension is it
x.shape

(8,)

In [74]:
# Slicing : start ,end , step 
y = x.reshape(4,2)
y

array([[ 1,  2],
       [ 3,  6],
       [ 7,  8],
       [ 9, 12]])

In [75]:
y[0:3]  


array([[1, 2],
       [3, 6],
       [7, 8]])

In [76]:
y[0:3,1]    # here 0 is first index which is [1,2],then :3 third row but as we know in slicking
            # third is exclued therefore 3 is consider as [7,8] , then 1 here is column it 
            # mean take number from 0 till three row but only column number one value which is 
            # [2,6,8]

array([2, 6, 8])

In [84]:
y[::2]   # if we want to silining only row which will be an alternative like it 
        # ignore [3,6,9,12] print 

array([[1, 2],
       [7, 8]])

In [85]:
y

array([[ 1,  2],
       [ 3,  6],
       [ 7,  8],
       [ 9, 12]])

In [86]:
y[::,0] # this is column vise rows we want 0, or 1 column because we have small data 


array([1, 3, 7, 9])

In [87]:
x

array([ 1,  2,  3,  6,  7,  8,  9, 12])

# now we want fancy indexing


In [94]:
x[[4,1,3,5,7]] #fancy indexing allows us to use an array of indices to access multiple array elements at once

array([ 7,  2,  6,  8, 12])

# vectorized Operations

In [98]:
import numpy as np
x = np.array([1,3,4,7])
y = np.array([2,5,6,8])
x+y

array([ 3,  8, 10, 15])

In [99]:
x-y

array([-1, -2, -2, -1])

In [100]:
x/y

array([0.5       , 0.6       , 0.66666667, 0.875     ])

In [101]:
x*y

array([ 2, 15, 24, 56])

In [102]:
x%y

array([1, 3, 4, 7])

In [103]:
x * y *3

array([  6,  45,  72, 168])

# Shape Pratice
### (1)
### 00000
### 11111
### 11111
### 11111
### 00000

In [127]:
x = np.ones((5,5))
x.astype('int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [128]:
x[0]=0
x[4] =0

In [129]:
x

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

# (2)
### 00000
### 01110
### 01110
### 01110
### 00000

In [130]:
x

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [140]:
y = np.zeros((5,5))
y.astype('int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [142]:
y[1:4,1:4] = 1
y

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])