In [2]:
import numpy as np

In [3]:
arr1 = np.zeros((2,10))

In [4]:
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
x=arr1+13
x

array([[13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.]])

In [6]:
arr2 = np.ones((2,10))

In [7]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
arr3 = x + arr2 
arr3.astype('float')

array([[14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [10]:
marks = np.array([23,45,65,14,63,67,86])
marks.astype('float')
np.where(marks>50,'pass','fail')

array(['fail', 'fail', 'pass', 'fail', 'pass', 'pass', 'pass'],
      dtype='<U4')

In [18]:
salary = np.array([1004,342,10002,2344,32343,32422,34222])
salary

array([ 1004,   342, 10002,  2344, 32343, 32422, 34222])

In [19]:
np.where(salary < 100000, salary*1.1,salary*0.5)

array([ 1104.4,   376.2, 11002.2,  2578.4, 35577.3, 35664.2, 37644.2])

In [20]:
import numpy as np 
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
x = arr.reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
x.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [29]:
x.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [30]:
arr = np.arange(1,101)
arr.mean()

50.5

In [31]:
import numpy as np
gender = np.array(['Male','Female','Male','Male','Female','Female'])

In [32]:
gender[gender == 'Male']

array(['Male', 'Male', 'Male'], dtype='<U6')

In [34]:
arr = gender == 'Male'

In [35]:
arr

array([ True, False,  True,  True, False, False])

In [36]:
arr.sum()

3

In [37]:
arr

array([ True, False,  True,  True, False, False])

In [39]:
arr.all()

False

In [41]:
arr.any()

True

In [42]:
arr = np.array([1,2,4,1,6,2,2,2,2,]) # for finding duplicate  


In [43]:
unq = np.unique(arr)
unq

array([1, 2, 4, 6])

In [44]:
np.save('arr',unq)

In [49]:
import numpy as np 
arr = np.arange(1,101),np.reshpe(10,10)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpe'

In [48]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])