In [5]:
import numpy as np 


In [6]:
py =  range(10000)

In [7]:
py

range(0, 10000)

In [8]:
numpy_array = np.arange(10000)

In [9]:
numpy_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [10]:
x = np.array(10)

In [11]:
x

array(10)

In [21]:
np.zeros([1])

array([0.])

In [29]:
for i in range(100):
    result = result  = numpy_array

In [35]:
x = np.zeros([10])
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
x+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [38]:
x = np.arange(1,10)

In [39]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x = range(100)

In [43]:
x

range(0, 100)

In [45]:
x = np.zeros((4,5,2))

In [46]:
x

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [47]:
x=np.zeros((4,5,2,6))  #"""(4,5,2,6)<-- this is tuple"""
x

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [48]:
x.shape

(4, 5, 2, 6)

In [49]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
x.shape

(12,)

In [51]:
x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [52]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
x.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [56]:
x.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [58]:
x.reshape(3,4,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [59]:
x.ndim

1

In [60]:
x.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [61]:
x.ndim

1

In [63]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
x.ndim

1

In [76]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape


(8,)

In [79]:
z = y.reshape(2,4)


In [80]:
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
z[0,2] # it give us 3 bcz we told hime givr me that number which is on 2 index here are we #array([[ 1,  2,  3,  4],


3

In [97]:
z[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
z[0::]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
z[::1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
z[::1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
z[0:1]

array([[1, 2, 3, 4]])

In [105]:
z[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [109]:
arr.shape

(2, 2, 3)

In [110]:
arr.itemsize

8

In [111]:
arr.size

12

In [117]:
arr1=arr.astype('float')
arr1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [118]:
arr1.dtype

dtype('float64')

In [123]:
np.empty(2)

array([-2.00000000e+000,  1.34842704e-315])

In [124]:

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(4,3)

In [125]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [126]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [134]:
y[2:3,2]

array([9])

In [139]:
y[1:2,1]

array([5])

In [137]:
y[::,2]

array([ 3,  6,  9, 12])

In [138]:
y[::,1]

array([ 2,  5,  8, 11])

In [140]:
y[::,0]

array([ 1,  4,  7, 10])

In [142]:
y[0,::]

array([1, 2, 3])

In [143]:
y[1,::]

array([4, 5, 6])

In [144]:
y[2,::]

array([7, 8, 9])

In [148]:
y[2:3,0:2]

array([[7, 8]])

In [156]:
y[0:1,1]

array([2])

In [159]:
y[0:1]

array([[1, 2, 3]])

In [167]:
x = np.zeros((5,5))

In [168]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [174]:
x[1:4]=1

In [175]:
x

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [232]:
x = np.ones((5,5))
x[1,1:2]=0 # 1 is row  # 1:2 is columns 

In [233]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [234]:
x = np.ones((5,5))
x[0:1]=0
x[4:5] = 0

In [235]:
x

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [236]:
x

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [237]:
x[0:5,4]=0
x[0:5,0]=0
#  x[1:4,1:4]

In [238]:
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [241]:
z = x[1:4,1:4]

In [242]:
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])