In [5]:
import numpy as np 
arr1 = np.zeros((2,10))

In [6]:
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
x = arr1 +13
x

array([[13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.]])

In [10]:
arr2 = np.ones((2,10))
arr2


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
y = arr2
y

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
arr3 = arr1 + arr2 
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
z = x + y
z.astype('int')

array([[14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
       [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]])

In [16]:
arr3 = arr1 * arr2 + 3 

In [17]:
arr3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

# Note
# np.where 

In [20]:
marks = np.array([34,56,78,99,67,89])
np.where(marks>60,'pass','fail')


array(['fail', 'fail', 'pass', 'pass', 'pass', 'pass'], dtype='<U4')

In [25]:
salary  = np.array( [ 10,20,30,15,25,50,40,25])
salary

array([10, 20, 30, 15, 25, 50, 40, 25])

In [26]:
np.where(salary>25,"top salary" ,'min salary')

array(['min salary', 'min salary', 'top salary', 'min salary',
       'min salary', 'top salary', 'top salary', 'min salary'],
      dtype='<U10')

In [28]:
incresment_salary = np.where(salary < 40, salary*1.1,salary*1.05)

In [29]:
incresment_salary

array([11. , 22. , 33. , 16.5, 27.5, 52.5, 42. , 27.5])

In [30]:
 ################### OR

In [31]:
salary = np.array([10000,8000,5000,15000,20000,250000,18000])
salary

array([ 10000,   8000,   5000,  15000,  20000, 250000,  18000])

In [32]:
increment_salary = np.where(salary < 20000, salary*1.1,salary*1.05)

In [33]:
increment_salary

array([ 11000.,   8800.,   5500.,  16500.,  21000., 262500.,  19800.])

In [35]:
increment_salary.dtype

dtype('float64')

In [36]:
increment_salary.astype('int')

array([ 11000,   8800,   5500,  16500,  21000, 262500,  19800])

In [46]:
import numpy as np 
arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Note 2
# T is transpose In transpose row convert in columns
### there are two method of find tranpse
### 1. arr.T and
### 2. arr.transpose() it is very importance topic we used it in matrix

In [63]:
arr.transpose() # row convert in columns and columns convert in rows


array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [64]:
arr 

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [62]:
arr2 = np.arange(0,12)
arr3 = arr2.reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
arr3.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Note 3
### Now We are going to find of mean of any array through using "Mean Function "
### formula of mean m = sum of the terms / number of terms

In [65]:
arr = np.arange(1,101)
arr.mean()

50.5

In [68]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [69]:
arr2  =  np.array([2,3,4,5,6,7,8,9,10])
arr2.mean()

6.0

In [72]:
arr.shape

(100,)

# cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis


In [75]:
arr = np.array([1,3,4,5,8])

In [76]:
arr.cumsum() # it work like our arr is [1,3,4,5,8] now this will add put the 1 after one
            # it goes to to add 1+3 =4 , 4 which was answer of previs value will be add to next number 
            # like 4+4 = 8 , so on 8 will be add to 5 which which our base arr now 5+8 = 13 then now the
            # 13 answer will be added in the 8 . which will be 13+8 =21 

array([ 1,  4,  8, 13, 21])

In [77]:
arr. cumprod() 
#It seems like there might be a typo in your question, and you might be referring 
#to "cumulative product" in NumPy. If so, you can use the numpy.
#cumprod() function to calculate the cumulative product of elements in an array. 

array([  1,   3,  12,  60, 480])

# Note 4
### 1. Function: A standalone block of code that performs a task and can be called by name.
### 2. Method: A function associated with a specific object or class, called on instances of that class.
### 3 Procedure Vs. Function
### 4. Procedure doesn't return any value
### 5. Function returns a value

# Note 5
### method for boolen arrays
### 1. sum(): counting True values in a boolean array
### 2. any(): tests whether one or more values in an array is True
### 3. all(): checks if every value is True

In [7]:
import numpy as np
gender = np.array(['Male','Female','Male','Male','Female','Female'])


In [8]:
gender  [gender == 'Male']


array(['Male', 'Male', 'Male'], dtype='<U6')

In [9]:
# for finding where where male take place we use
arr = gender == 'Male'
arr

array([ True, False,  True,  True, False, False])

In [10]:
arr.sum()

3

In [11]:
arr

array([ True, False,  True,  True, False, False])

In [12]:
arr.all()

False

In [13]:
arr.any() 

True

In [14]:
arr = np.array([2,4,10,20,16])


In [15]:
x = (arr%2 == 0) # findin reminder if the value reminder is 0 then print true


In [16]:
x

array([ True,  True,  True,  True,  True])

# NOTE 6
### Universal quantifier
### Existential quantifier
### 1. Universal Quantifier (∀):
### Use all() to check if a condition holds for every element in an iterable.
### Example: all(x > 0 for x in numbers).
### 2. Existential Quantifier (∃):
### Use any() to check if there exists an element in an iterable that satisfies a ### condition.
### Example: any(x > 0 for x in numbers).

In [17]:
arr.sort()  # inplace # WE USED SORTING FOR TIME SERIES

In [18]:
arr

array([ 2,  4, 10, 16, 20])

In [19]:
arr[::-1] # inverse

array([20, 16, 10,  4,  2])

In [26]:
arr = np.array([1,2,4,1,6,2,2,2,2,]) # for finding duplicate  

In [27]:
arr

array([1, 2, 4, 1, 6, 2, 2, 2, 2])

In [28]:
uniq = np.unique(arr)# for finding duplicate 
uniq

array([1, 2, 4, 6])

In [30]:
np.save('data',uniq) # saving the file

In [32]:
contant =np.load('data.npy') # loading that save file 
contant

array([1, 2, 4, 6])

In [33]:
#Saving multiple arrays


In [39]:
import numpy as np
arr = np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
arr.diagonal() # it give us those diagonal value 

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [46]:
arr.trace()

505

 # Difference between ravel and flatten
 ### Flatten always produces a one-dimensional copy, whereas ravel attempts to provide a one-dimensional view of the original matrix. Be cautious since altering the returned matrix from ravel may make changes to the original matrix. Modifying the content of the array created by flatten has no effect on the original array

In [47]:

import numpy as np
 
# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])
 
# Let's print the array a
print ("Original array:\n ", a)
 
# Convert nd array to 1D array
c = a.flatten()
 
# Flatten passes copy of
# original array to 'c'
print ("\nFlatten array using flatten: ", c)

Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using flatten:  [1 2 3 4 3 1 4 2]


In [48]:
import numpy as np
 
# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])
 
# Let's print the array a
print ("Original array:\n ", a)
 
ra = np.ravel(a)
print ("\nFlatten array using ravel: ", ra)

Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using ravel:  [1 2 3 4 3 1 4 2]
