In [40]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [39]:
print(type(arr1))

<class 'numpy.ndarray'>


In [31]:
np.ndim # 1 dim 

<function numpy.ndim(a)>

In [17]:
import numpy as np
arr3 = np.zeros((5,2))

arr3

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
arr4 = np.ones((3,5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
arr5 =np.arange(5,16,2) # increment with 2 
arr5

array([ 5,  7,  9, 11, 13, 15])

In [30]:
arr6 = np.linspace(2,10,7) #1 start 2 end  3 number of splites=  ki kis hisbo ma tona ha 
arr6

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [37]:
arr6.shape


(7,)

In [36]:
arr5.shape


(6,)

In [35]:
arr4.shape

(3, 5)

In [38]:
arr3.shape

(5, 2)

In [61]:
arr7 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr7

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr7.shape # total number 2 , total pair 2 total column 3

(2, 2, 3)

In [56]:
arr7.ndim

3

In [59]:
arr7.size# total number of element 

12

In [62]:
arr7.itemsize # total number of row 

4

In [63]:
arr7.astype('float') #convert the datatype

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [66]:
arr7 =np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13],[14]]])
arr7

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (1, 4, 2) + inhomogeneous part.

In [ ]:
[1,2],[3,4]],[[5,6],[7,8]